---
- name: Jenkins controller setup
  hosts: jenkins-controller
  become: true
  tasks:
    - name: Update all packages to latest
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Download jenkins key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add jenkins repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins.list

    - name: Update all packages to latest
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Install fontconfig
      ansible.builtin.shell: |
        apt install fontconfig -y
    
    - name: Install java
      ansible.builtin.shell: |
        apt install openjdk-17-jre -y
        java -version

    - name: Install jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Start service jenkins, if not started
      ansible.builtin.systemd_service:
        name: jenkins
        state: started

    - name: Enable service jenkins
      ansible.builtin.systemd_service:
        name: jenkins
        enabled: true


